# Generated by Django 4.2.1 on 2023-06-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='contact-list')),
                ('facebook', models.CharField(max_length=300)),
                ('whatsapp', models.CharField(max_length=300)),
            ],
        ),
    ]
